odin: Drop liblbs_core.so
Since the QPR2 merge, SubscriptionManager have been changed and handler is no more used.

Fix this issue

03-17 12:51:24.495 26599 26616 E AndroidRuntime: FATAL EXCEPTION: IZatServiceContext
03-17 12:51:24.495 26599 26616 E AndroidRuntime: Process: com.qualcomm.location, PID: 26599
03-17 12:51:24.495 26599 26616 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getHandlerExecutor()Lcom/android/internal/telephony/util/HandlerExecutor; in class Landroid/telephony/SubscriptionManager$OnSubscriptionsChangedListener; or its super classes (declaration of 'android.telephony.SubscriptionManager$OnSubscriptionsChangedListener' appears in /system/framework/framework.jar!classes3.dex)

Change-Id: Ic9924a871d7c5167227eb9ad06292a23d0fed41c